### ISSUE TITLE
what are the commands?

### ISSUE THREAD

**Issue by 26souravk** [dcdunkan/gd-tgbot1#1]
I dont know the commands, kindly provide commands

**Comment by dcdunkan** [comment]
['download', 'd
e = ['authorize',
['setfolder',
['revoke']
['clone', 'clone']
['delete', 'del']
sh
h =
emptyTrash'
"ytdl'

**Comment by dcdunkan** [comment]
help
start
download
authorize
setfolder
revoke
clone
delete
emptyTrash
ytdl

**Comment by dcdunkan** [comment]
start
help
download
authorize
setfolder
revoke
clone
delete
emptyTrash
ytdl
